Seneca-ICTOER/Intro2C

docs/weeklyContents.md

Fixes #17 
Used `<ul>` `<li>` for the list.
Final result:

Improve format in weekly schedule

---

package.json
yarn.lock

Part of Issues #11 
Upgrade docusaurus version to  2.0.0-beta.8
Did some testing, did not see any breaking changes

Upgrade docusaurus 2.0.0-beta.8

---

docs/D-Modularity/functions.md
src/css/custom.css

Hi there I have found some issues to fix in the page and have fixed them.
Fixes #26 
The changes I made were:
* Added ":" to a few "For example" lines
* Fixed typo of parameter under **Function Calls**
* Added missing inline code blocks to **Caller Function** examples
* Code blocks were missing "c" identifier so the colors were uneven
* Added address symbol using "&amp;" to walkthrough tables
* Fixed the "Notes" to use admonitions from markdown
* Removed extra space from some of the code blocks (it was probably the parser that did it)
* Added tbody/thead because of React JSX errors in the console.
* Added alt tags to images
* Created a <span> element to wrap around images to make the background white. This was for dark mode compatibility.
* Changed "class" and "colspan" to their React …

Issue 26- auditing and fixing functions.md

---

docusaurus.config.js

Address comment in #60, and issue #18 for all pages.

Fix comment visibility in code blocks

---

docs/F-Refinements/algorithms.md

Fix #28 
- Fix Frontmatter for page to include `id`, `title`, `slug`, and `description`
- Replace `**...**` used as a fourth heading level with `####`
- Fix all code to be wrapped with backticks
- Replace blockquote with Admonitions for clarity
- Include inter-site links to relevant pages
- Fix typo

Audit & fix `algorithms.md` page

---

docs/F-Refinements/string-library.md

Here are some modifications I made to fix #29 :
* Fix typo
* Replace block quotes with admonitions
* Remove extra white spaces in code blocks
* Fix frontmatter
* Add inter-site links to other page
* Add bold emphasis for some words

Audit and fix `string-library.md`

---

docs/A-Introduction/computers.md

Fixes #45
Steps done to modify and check `computers.md`:
- Fixed a few typos
- Added alt text for diagram images
- Horizontally centered images
- Added links to mentioned chapters in Outline section
- Ran page through Lighthouse and Web Hint
- Checked mobile and desktop versions (Dark and Light modes)

Audit and Fixed `computers.md`

---

docs/Resources-Appendices/operators.md

Hey, 
This addresses #42.
I tried to improve this md file following what Professor David suggested.
What I did:
Fixed typos.
Checked for desktop and mobile.
Checked for Light and Dark mode.
Improved readability for the md file.
Checked it on Lighthouse:
Thank you for considering this.
Please let me know what else could be improved.

Audit and Fix - Operators.md - Issue 42

---

docs/F-Refinements/more-input-and-output.md

Fix #82 
Main changes are:
- Fix typos
- Add Frontmatter
- Add inter-site links
- Replace block quotes with admonitions
- Add alt tag/descriptive text for links
- Add backticks to code and memory addresses in tables
- Replace `**...**` used as headings with heading level `####`
Other steps to check:
- Ran through [Lighthouse](https://developers.google.com/web/tools/lighthouse) and [Web Hint](https://webhint.io/))
- Checked light/dark modes in desktop and mobile

Fix and Audit `More Input and Output.md`

---

docs/B-Computations/expressions.md

Fixes https://github.com/Seneca-ICTOER/IPC144/issues/39
- Added alt text to images
- Fixed grammar
- Added surrounding backticks to types
- Added frontmatter
- Changed blockquote for admonition

Audited and fixed expressions.md

---

docs/B-Computations/testing-and-debugging.md

Solves issue #86 which is a sub-task of issue #18. 
I have audited and fixed an existing Markdown file `docs/testing-and-debugging.md`. 
What have been done: 
- Fixed typos
- Added Frontmatter metadata
- Added and fixed code blocks
- Removed unnecessary backticks, wrapped function names in backticks
- Added alt tags for all images
- Added inter-site links to other pages
- Changed syntax highlighting

Audit and Fix `testing-and-debugging.md`:

---

docs/D-Modularity/output-functions.md

Hi, this fixes #87 
This PR is an audit of output-functions.md file. I mainly added and fixed the below.
- Fix typos
- Remove extra spaces
- Unify markdown syntax
- Improve readability on the markdown file
- Check display (desktop/mobile/dark and light mode)
- Run the page through Lighthouse and Web Hint
- Added alt text to images
- Fix Frontmatter for the page to include proper id, title, and slug
- Remove extra indentation from code blocks
If I need to improve, please let me know! Thank you so much.

Audit output-functions.md

---

docs/F-Refinements/portability.md

Fixed [#94](https://github.com/Seneca-ICTOER/IPC144/issues/94).
Some changes I made:
-  Add Frontmatter
- Add descriptive text for image
- Fixing Typos and Spelling Mistakes
- Add More Fixes Typos
- Replace Block Quotes with Admonitions
- Add inter-site link

Audited and Fixed `portability.md`

---

docs/F-Refinements/two-dimensional-arrays.md

Refer to the issue #88 
What I've done:
+ Break sentences with one space instead of two spaces
+ Add alt text to the image
+ Reset the indentation of all code examples
+ Remove all <br/ >
+ Improve the readability(Highlight some important reading words)
+ Adjust the for loop code
Things I can't accomplish:
+ Can't set the image to looking good in dark mode
+ Can't set the commented lines in code example perform good in dark mode

Audit two-dimensional-arrays.md

---

docs/F-Refinements/character-strings.md

Fix #99 
In this PR I have:
- Adding id, title and description for the doc
- Fix typo and adding more explanation
- Emphasis using `<strong>` instead of `<b>`
- Fix code indentation
- Invalid link to `ASCII` and `EBCDIC` markdown doc

Character-string.md fixed for clarification

---

docusaurus.config.js
pwaCustomButton.js

Part of Issues #11 
For more visibility, we decided to add a button to install the app
https://user-images.githubusercontent.com/58233223/144284965-0f1c7c36-d1d2-4da2-ab5a-218c38395b38.mp4

Add custom PWA button

---

.github/workflows/pull_requests.yaml

run yarn build, prettier-check on every PR in GitHub Actions

---

src/css/custom.css

Fixes #127 
Adds css to table elements to be centred in their page.

Added CSS to centre all tables

---

docs/E-Secondary-Storage/text-files.md

Fixes #122
- Fixed typos and grammar
- Checked Desktop, Mobile, Light & Dark
- Checked Lighthouse and Web Hint
- Added better alt tags for images
- Changed blockquotes to use Admonitions
- Added inter-site links
- Added Frontmatter

Audit and Fixed text-files.md

---

docs/Resources-Appendices/data-conversions.md

Fixes #123
- Checked for typos and grammar errors
- Checked page in desktop, mobile, light & dark
- Checked using Lighthouse & Web Hint
- Added alt tags to images
- Added Frontmatter
Note:
The tables are kept as HTML tags due to formatting requirements. Markdown tables cannot have merged cells in a row and cannot have no header row. Table formatting as seen below:

Audit and Fix data-conversions.md

---

docs/D-Modularity/library-functions.md
docs/D-Modularity/output-functions.md
docs/F-Refinements/character-strings.md
docs/F-Refinements/more-input-and-output.md

I added some missing admonitions in three files:
- `output-functions.md`
- `library-functions.md`
- `character-strings.md`

Fixed #150: Add missing admonitions

---

docs/B-Computations/types.md

Co-authored-by: Minh Pham <est2000vn@gmail.com>
Finishing work from https://github.com/Seneca-ICTOER/IPC144/pull/102

Audit and Fix types.md

---

convert-to-pdf.sh

fix: paginationSelector for PDF generation
