vercel.json
This should reduce the spam we get from Vercel for all the PR preview builds.  It also allows the build logs to be accessed by the public vs only @CameronGray1210, which is helpful for debugging build errors in PRs.
=> Add vercel.json to silence notifications, allow public access to logs

docusaurus.config.js
Fixes #16 
This PR adds `maxHeadingLevel` to 4 to allow `<h4>` in the table of contents.
After making this change I noticed that some of the sections can look a bit messy. For example in `docs/B-Computations/logic.md`:
Some of the `Example` subtitles could be changed to **bold** instead of `<h4>`. Let me know what you think.
=> Fix #16. Add maxHeadingLevel to tableOfContents

docs/B-Computations/a-simple-calculation.md, docs/B-Computations/expressions.md, docs/B-Computations/logic.md
Fix #35.
This PR replaces all level 4 heading for Example to **bold**. This removes examples from the table of content.
=> Fix #35: Replace h4 to bold for all Examples

docs/intro.md, docusaurus.config.js
Solve Issue #54 
I added hyperlink of **Weekly Schedule** to the footer in *docusaurus.config.js*.
I removed hyperlink of **Weekly Schedule** in **Contents** page in *docs/intro.md*.
=> Add Weekly Schedule to footer

convert-to-pdf.js, convert-to-pdf.sh, package.json, yarn.lock
Fixes #14 
I use [mr-pdf](https://github.com/kohheepeace/mr-pdf) to convert the Docusaurus docs into a pdf file [Seneca-IPC144.pdf](https://github.com/Seneca-ICTOER/IPC144/files/7491025/Seneca-IPC144.pdf).
`mr-pdf` requires a running instance of the website either `localhost` or an address on the net, it is specified at 
`--initialDocURLs`. 
`--initialDocURLs`, `--contentSelector`, `--paginationSelector` are required options but there's no need to edit the last two
```bash 
npx mr-pdf --initialDocURLs="http://localhost:3000" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a" --coverImage="https://download.logo.wine/logo/Seneca_College/Seneca_College-Logo.wine.png" --coverTitle="IPC144" --outputPDFFilename …
```
=> Added a shell script that converts Docusaurus doc to pdf

docs/D-Modularity/functions.md, docs/D-Modularity/input-functions.md, src/css/custom.css
This PR is an audit of `input-functions.md`:
* Add alt text to images 
* Encase key words in backticks
* Add missing '-'
* Remove extra indentation from code blocks
* Add missing comma
* Remove empty bullet point
* Add title to frontmatter
* Improve image centering
* Add descriptive text to link
* Add div.mdImg class for image centering
For the image centering, I went with the `text-align: center` approach which requires the image to be in a `div` tag. So I combined the existing `.mdImg` class with a `div.mdImg` class that does the centering. Because of this, I had to change the `span` tags in `functions.md` to `div` tags. Everything works as expected.
Let me know if I missed anything.
Fixes #33
=> Audit input-functions.md

docs/A-Introduction/compilers.md
Fixes #43 
* Fix typos, Markdown syntax
* Fix Frontmatter metadata
* Adding  inter-site links to other pages that have related info
* Add alt text on images
* Improve page's Accessibility
=> Audit and fix compilers.md

docs/B-Computations/a-simple-calculation.md
Fixes #38 
* added alt tag, backticks
* used admonitions
* fixed markdown syntax
* fixed typo
* updated Frontmatter
* removed unnecessary <b>
=> Audit & fix `a-simple-calculation.md`:

CNAME, docusaurus.config.js, static/CNAME
References to the old "cghub.ca" is now updated to point to the "ipc144.sdds.ca" domain in preparation for production builds and releases.
=> Cameron gray1210 sdds domain

.github/workflows/deployment.yaml, .gitignore, CONTRIBUTING.md
Fix #13 
Create .github/workflows/deployment.yaml to have the production site get updated automatically on every push/merge to the main branch.
Current progress:
=> create github actions for deployment

docusaurus.config.js
Part of #106.  This changes our config so that we warn, but don't crash, when doing a production build.  In #107 we can re-enable this; but for now this lets us build things without crashing.
=> Warn on broken links only, don't throw

docs/D-Modularity/library-functions.md
Part of #18
Audit and fix library-functions.md
Check List
=> Audit and fixed library-functions.md #105

docusaurus.config.js
Fixes #136 
- Change PWA link name from: "Add to Home Screen" to: "Install as an App"
=> Change PWA link name

docs/A-Introduction/compilers.md, docs/A-Introduction/computers.md, docs/A-Introduction/information.md, docs/B-Computations/a-simple-calculation.md, docs/B-Computations/expressions.md, docs/B-Computations/logic.md, docs/B-Computations/style-guidelines.md, docs/B-Computations/testing-and-debugging.md, docs/C-Data-Structures/arrays.md, docs/C-Data-Structures/structures.md, docs/D-Modularity/functions-arrays-and-structs.md, docs/D-Modularity/library-functions.md, docs/D-Modularity/output-functions.md, docs/D-Modularity/pointers.md, docs/E-Secondary-Storage/records-and-files.md, docs/F-Refinements/algorithms.md, docs/F-Refinements/more-input-and-output.md, docs/F-Refinements/pointers-arrays-and-structs.md, docs/F-Refinements/portability.md, docs/F-Refinements/string-library.md, docs/F-Refinements/two-dimensional-arrays.md, docs/Resources-Appendices/operators.md, docusaurus.config.js
Fixes #106 
- By removing slug fixed all the broken links on build
- Enable `onBrokenLinks`  to throw
=> Fix broken links

docs/B-Computations/types.md, docs/D-Modularity/functions-arrays-and-structs.md, docs/D-Modularity/functions.md, docs/D-Modularity/pointers.md, docs/F-Refinements/character-strings.md, docs/Resources-Appendices/data-conversions.md, src/css/custom.css
Closes #112 
Changes:
- Created CSS class for cell highlighting using two different colours (light vs dark mode)
- Added white background to images in dark mode
Before:
After:
=> Update style for tables and images

docs/F-Refinements/more-input-and-output.md
I checked `more-input-and-output.md` file, and there is syntax error in the `Remarks` note, the admonition `:::` has extra white space, and that is the reason why half of the page is "admonitioned".
This is the issue the page currently having now
And after removing extra white space in `more-input-and-output.md` file:
=> Fix admonition in more-input-and-output file

.gitattributes
This will change how git works locally, using Unix end-of-line characters vs. whatever OS the user is working on.  Doing so will mean that Prettier won't complain about all files being in the wrong format.
You can read more about how this works at https://git-scm.com/docs/gitattributes#_text.
=> Force git to use Unix end-of-line via .gitattributes

convert-to-pdf.js, package.json, yarn.lock
This fixes #168, updating the https://www.npmjs.com/package/mr-pdf to 1.0.8 to pick up the fix for missing images in https://github.com/kohheepeace/mr-pdf/pull/36.
I've tested it locally, and images now load, though there are still some rough edges in how the images are shown in certain cases.  I think this is more to do with CSS that needs to be applied better.
I've also pinned prettier to 2.5.1 so that there isn't so much churn on styling changes.
=> Fix #168: update mr-pdf to 1.0.8 for images in PDF

package.json, yarn.lock
What does this PR do?
- It upgrades the library versions that `Docusaurus` ships with to the latest versions that work together correctly
- Removes `^` from `@docusaurus/plugin-pwa`. It should always be on the same version as `@docusaurus/core`
- adds `@docusaurus/module-type-aliases` to `devDependencies`, as a new project that is created by `create-docusaurus@latest` includes this, and it seems to be an integral part of the project
Tested with both local development and `build` - `serve`
closes #175
=> chore: Upgrade Docusaurus and related library versions

convert-to-pdf.sh, docusaurus.config.js
This PR fixes #163. 
I added `mv` in shell script so that it can be moved during `yarn serve-convert`. 
Also the footer link is updated too. My test result looks good.
=> Upate shell script to move pdf to static and the download link

docusaurus.config.js
When I updated the copyright info in https://github.com/Seneca-ICTOER/Intro2C/issues/132, I made a mistake and missed that we also have the copyright in the site's footer.  I've corrected that here.
Apologies for missing this, it wasn't intentional.  I'd appreciate pointers to any other places where I've made this same mistake.  I can't see any, but I missed this one.
=> Update docusaurus.config.js copyright to match LICENSE.md
